/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package BmxWavExtractor;

// public class AppUnrouted {

    public String message = "App did not perform any tasks";

    public String getGreeting() {
        return "Hello world."
    }



    private InputStream readInputFile {
        File initialFile = new File("src/main/resources/sample.txt");
        InputStream targetStream = new FileInputStream(initialFile);
        return InputStream inputStream = classLoader.getResourceAsStream("fileTest.txt");
        final File initialFile = new File("src/test/resources/sample.txt");
        final InputStream targetStream =
                new DataInputStream(new FileInputStream(initialFile));
    }

    private String readFromInputStream(InputStream inputStream)
            throws IOException {
        StringBuilder resultStringBuilder = new StringBuilder();
        try (BufferedReader br
                     = new BufferedReader(new InputStreamReader(inputStream))) {
            String line;
            while ((line = br.readLine()) != null) {
                resultStringBuilder.append(line).append("\n");
            }
        }
        return resultStringBuilder.toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
